---

- name: Include os family-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: linux-ima.yml
- import_tasks: linux-evm.yml
# - import_tasks: linux-fsverity.yml
